export enum ETitleFields {
    STATE = 'Стан',
    NO_DATA = 'немає даних',
    MIXING_NUMBER = 'Номер змішування',
    NEW = 'Новий',
    COMPONENT_ADDED = 'Компонет додан',
    MIXING_IN_PROCESS = 'Перемішування в процесі',
    ADMITTED_TO_PRODUCTION = 'Допущений у виробництво',
    PAUSE = 'Перемішування пауза',
    NOT_ALLOWED_TO_PRODUCTION = 'Не допущено у виробництво',
    ENDS = 'Закінчилася',
    SENT_TO_ANALYSIS = 'Проба відправлена на аналіз',
    GOT_RESULT_ANALYSIS = 'Отримано результат аналізу',
    ANALYSIS_IS_COMPLETE = 'Аналіз завершений',
    COMPOUND_ENDED = 'Склад мішки закінчився',
  }