export enum MainTitles {
  NO_DATA = 'Немає даних',
	ADD_COMPONENT = 'Додати компонент',
	MIXING = 'Замішування',
	COMPONENT_NAME = 'Назва компонента',
	WEIGHT = 'Вага (кг)',
	APPROVE_FOR_USE = 'Допустити у виробництво',
	MIXING_END = 'Завершети замішування',
	ADD_TO_MIXER = 'Додати час',
	MIXER_NAME = 'Назва міксера',
	REJECT_FOR_USE = 'Зняти з виробництва',
	MIXING_TYPE = 'Тип складу замішування',
	MIXING_NUMBER = 'Номер замішування',
	BATCH_PLACE = 'Місце у Партії',
	CHOOSE_MIXER = 'Вибрати міксер',
	SEND = 'Надіслати',
	ADD_MIXING = 'Додати замішування',
	ND_NUMBER = 'Нормативний документ',
	BACK_TO_THE_MIXING = 'Назад до замішування',
	CONFIRM = 'Подтвердить',
	MIXING_AT = 'Змішуеться у',
	ANALYSIS = 'Аналізи',
	TYPE_NAME = 'Назва складу',
	MIXING_DATE = 'Дата додавання до системи',
	START_TIMER = 'Запустити таймер',
	ADD_MINUTES = 'Встановити хвилини',
	ADD_HOURSE = 'Встановити годину',
	CREATED_AT = 'Створено',
	VALIDATE_NUMBER = 'Значення не може бути бильше за 8 символів',
	CHOOSE_MINUTES = 'Встановити хвилини',
	
}