export enum ETitleFields {
    noData = 'немає даних',
    number = '№ Прес-форми',
    detailType = 'Тип',
    state = 'Стан',
    lastGeometricMeasurement = '№ акта вхідного контролю',
    passport = '№ формуляра',
    numberND = '№ НД',
    createAt = '',
    updateAt = '',
    aap = 'Поточне ААП',
    place = 'Місце полімеризації',
    KM1 = 'Поточне заповнення з змішування КМ-1',
    submitControl = 'надіслаті на вхідний контроль',
    defectDescription = 'Опис дефектів',
    buttonCreate = 'Створити',
    buttonCancelCreate = 'Скасувати',
    buttonSaveCreate = 'Зберегти',
    helperTextSelectTypeDetailTzp = 'Виберіть тип деталі',
    helperTextSelectNumberND = 'Виберіть № НД',
    createTitle = 'Додати нову пресс форму деталі ТЗП'
}